name: GitHub-Profile-3D-Contrib

on:
  schedule:
    # Runs at 4:00 AM and 10:00 PM ET daily (9:00 AM UTC and 3:00 AM UTC)
    - cron: "0 9 * * *"  # Morning update
    - cron: "0 3 * * *"  # Evening update
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PROFILE_3D_TOKEN }}  # Use the PAT for repo access

      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.PROFILE_3D_TOKEN }}  # Use the PAT for repo access
          USERNAME: ${{ github.repository_owner }}

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "🖼️ Generate 3D Contribution Graph" || echo "No changes to commit"
          git push || echo "Push failed, likely no changes to push"
