name: GitHub-Profile-3D-Contrib

on:
  schedule:
    # Runs at 6:00 AM and 6:00 PM UTC daily
    - cron: "0 4 * * *"  # Morning update
    - cron: "0 18 * * *" # Evening update
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PROFILE_3D_TOKEN }}  # Use the new secret

      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.PROFILE_3D_TOKEN }}  # Use the PAT for repo access
          USERNAME: ${{ github.repository_owner }}

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "🖼️ Generate 3D Contribution Graph"
          git push
