name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 9 * * *"
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.PROFILE_3D_TOKEN }}
          USERNAME:     ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "🖼️ Generate 3D Contribution Graph" || echo "No changes to commit"
          git push || echo "Push failed, likely no changes to push"
