name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 11 * * *"  # 6:00 AM ET (11:00 AM UTC)
    - cron: "0 3 * * *"   # 10:00 PM ET (3:00 AM UTC)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PROFILE_3D_TOKEN }}  # Use the new PAT

      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.PROFILE_3D_TOKEN }}  # Use the PAT for repo access
          USERNAME: ${{ github.repository_owner }}

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull --rebase origin main
          git add -A .
          git commit -m "🖼️ Generate 3D Contribution Graph" || echo "No changes to commit"
          git push
