name: TryHackMe Update Badge

on:
  schedule:
    - cron: '0 0 * * *'   # every day
  workflow_dispatch:

permissions:
  contents: write

jobs:
  tryhackme-badge-update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Ensure assets folder exists
        run: mkdir -p assets

      - uses: p4p1/tryhackme-badge-workflow@main
        with:
          username: "havok"
          image_path: "./assets/thm_propic.png"
          GITHUB_TOKEN: ${{ secrets.PROFILE_3D_TOKEN }}

      - name: Commit THM badge (initial and updates)
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull --rebase
          git add assets/thm_propic.png
          git commit -m "⚡ Update TryHackMe badge" || echo "No changes to commit"
          git push || echo "Nothing to push"
